id: P97276219
initial_creation_type: ocr
source_metadata:
  volumes:
    ff0b2752dc9d49548586daba21c40189:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: གནོད་པ་བ་ཆེན་པོས་ཀ་མ་ལ་ཤཱི་ལ་ལ་གནད་ཀྱི་གདམས་པ་བསྟན་པ།
      total_pages: 1953
      volume_number: 27
