id: D844F0A02
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-06T09:35:35+00:00'
last_modified: '2022-05-26T11:35:23.625685+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '8744':
      image_group_id: I1PD95872
      title: གནོད་པ་བ་ཆེན་པོས་ཀ་མ་ལ་ཤཱི་ལ་ལ་གནད་ཀྱི་གདམས་པ་བསྟན་པ།
      total_pages: 1953
      order: 27
      base_file: 8744.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
